"""Initial migration for projects app."""
# Generated by Django 5.2 on 2025-07-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration to create Project model."""

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("transactions", "0002_tagtransactions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("notes", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("analyzing", "Analyzing"),
                            ("in_development", "In Development"),
                            ("testing", "Testing"),
                            ("finished", "Finished"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("conclusion", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="companies.company",
                    ),
                ),
                (
                    "transactions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
