# Generated by Django 5.2 on 2025-05-08 23:09
"""Initial migration for creating the Company model."""

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Initial migration class for the companies app.

    Creates the Company model with its initial fields.
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="companies", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
