"""Migration to add TagTransactions model."""
# Generated by Django 5.2 on 2025-07-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to create TagTransactions model with many-to-many relationship."""

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagTransactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transactions",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="transactions.transaction"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag Transaction",
                "verbose_name_plural": "Tag Transactions",
            },
        ),
    ]
